trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: HelloWorld
  displayName: Say Hello
  jobs:
  - job: HelloJob
    displayName: Print Hello
    steps:
    - script: echo Hello, World!
      displayName: 'Echo Hello'