trigger:
- main

variables:
  APP_NAME: 'latex-ai-backend'
  ANOTHER_VAR: 'another_value'

pool:
  vmImage: ubuntu-latest

stages:
- stage: RunDockerContainer
  displayName: Run the Docker container
  jobs:
  - job: RunJob
    displayName: Pull and Run
    steps:
    - script: |
        echo "Pulling the Docker image..."
        docker pull aayushgid/krivisio_ai:latest
      displayName: 'Pull Docker Image'
      
    - script: |
        echo "Running the Docker container..."
        # Pass variables to Docker using the -e flag
        docker run -d \
          -e APP_NAME=$(APP_NAME) \
          -e ANOTHER_VAR=$(ANOTHER_VAR) \
          -e SECRET_KEY=$(SECRET_KEY) \
          aayushgid/krivisio_ai:latest
        echo "Container should now be running."
      displayName: 'Run Docker Container'