import os
from dotenv import load_dotenv

# Load environment variables from a .env file
load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "your-default-key")
KRIVISIO_GITHUB_TOOL = os.getenv("KRIVISIO_GITHUB_TOOL", OPENAI_API_KEY)
KRIVISIO_REPORT_GENERATION_TOOL = os.getenv("KRIVISIO_REPORT_GENERATION_TOOL", OPENAI_API_KEY)
KRIVISIO_STRUCTURE_GENERATION_TOOL = os.getenv("KRIVISIO_STRUCTURE_GENERATION_TOOL", OPENAI_API_KEY)
KRVISIO_SIDE_TOOLS = os.getenv("KRVISIO_SIDE_TOOLS", OPENAI_API_KEY)
KRIVISIO_TALENT_MATCHING_TOOL = os.getenv("KRIVISIO_TALENT_MATCHING_TOOL", OPENAI_API_KEY)